version: '3'

services:
  db:
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_HOST: localhost
      POSTGRES_DB: postgres
    volumes:
      - db_volume:/var/lib/postgresql
    ports:
      - "5432:5432"
 
volumes:
  db_volume:
